name: freecad
channels:
  - conda-forge
dependencies:
  - boost
  - boost-cpp[version='>=1.78.0,<1.78.1.0a0']
  - clang_osx-arm64
  - clangxx_osx-arm64
  - cmake
  - coin3d
  - conda-build
  - conda-smithy
  - debugpy
  - doxygen
  - freetype[version='>=2.12.1,<3.0a0']
  - gmsh
  - graphviz
  - hdf5[version='>=1.12.2,<1.12.3.0a0']
  - matplotlib
  - ninja
  - numpy
  - occt[version='>=7.6.3,<7.7.0a0']
  - openssl==3.0.8
  - pcl[version='>=1.13.0,<1.13.1.0a0']
  - pip
  - pivy
  - pkg-config
  - ply
  - pybind11
  - pyside2
  - python_abi=3.11[build=*_cp311]
  - python[version='>=3.11,<3.12.0a0']
  - pyyaml
  - qt-main[version='>=5.15.6,<5.16.0a0']
  - qt-webengine[version='>=5.15.4,<5.16.0a0']
  - six
  - smesh[version='>=9.9.0.0,<9.9.1.0a0']
  - swig
  - vtk[version='>=9.2.2,<9.2.3.0a0']
  - xerces-c[version='>=3.2.4,<3.3.0a0']
  - zlib
  - pip:
    - ptvsd==4.3.2
